# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

ENV["COCOAPODS_DISABLE_STATS"] = "true"

target 'bundle' do
  pod 'JLRoutes'
end